# Generated by Django 2.2.3 on 2019-07-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ideias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideias',
            new_name='Ideia',
        ),
    ]
