# Generated by Django 2.2.3 on 2019-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190726_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
