# Generated by Django 2.2.3 on 2019-07-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190729_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
    ]
